name: daddylive-events-epg-grabber
on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch: # Allows manual trigger from the Actions tab

env:
  EPG_FILENAME: daddylive-events-epg.xml
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fetch_epg_job:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Manila

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install curl_cffi httpx pytz python-dateutil

      - name: Download and Run Python Script
        run: |
          curl -o daddylive-events-epg-grabber.py "${{ secrets.DADDYLIVE_EVENTS_EPG_URL }}"
          python daddylive-events-epg-grabber.py

      - name: Check if epg is generated successfully
        run: |
          file="epgs/${{ env.EPG_FILENAME }}"
          if [ -f "$file" ]; then
            echo "$file generated successfully."
            ls -lh "$file"
          else
            echo "Failed to generate $file."
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add "epgs/${{ env.EPG_FILENAME }}"
          git diff --staged --quiet || git commit -m "Update epg"
          git push --force
